mixed-port: 7890
ipv6: false
# allow-lan: true
# unified-delay: false
# tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
dns:
  enable: true
  listen: :1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter: ['*', '+.lan', '+.local']
  nameserver: [223.5.5.5, 114.114.114.114]
  fallback: [tls://1.1.1.1, tls://8.8.8.8]
  fallback-filter:
    geosite: [cn]
tun:
  enable: true
  stack: system
  dns-hijack: ['any:53']
  auto-route: true
  auto-detect-interface: true
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
proxies:
  - {name: 🇺🇸美国 x0.1, server: 12.34.56.78, port: 443, type: trojan, password: 5h98y93r9138ur87}
proxy-groups:
  - {name: normal, type: select, proxies: [🇺🇸美国2 x0.1]}
  - {name: crucial, type: select, proxies: [🇭🇰 香港 | V1 | 02]}
rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,github.dev,crucial
  - IP-CIDR,12.34.56.78/32,crucial
  - MATCH,normal
