#!/bin/sh
if [ "$1" = "init" ]; then
[ ! -e clash.gz ] && curl -o clash.gz -L https://github.com/Dreamacro/clash/releases/download/v1.18.0/clash-linux-amd64-v3-v1.18.0.gz
[ ! -e subconverter.tar.gz ] && curl -o subconverter.tar.gz -L https://github.com/tindy2013/subconverter/releases/download/v0.8.1/subconverter_linux64.tar.gz
rm -rf inner
mkdir -p inner inner/subconverter
cd inner
gzip -d <../clash.gz >clash
chmod +x clash
tar -xf ../subconverter.tar.gz --strip-components 1
cat <<EOF >generate.ini
[profile_1]
target=clash
path=config.yaml
url=https://dy.xfltd.cc/api/v1/client/subscribe?token=xxxxxxxxxxxxxxxx
EOF
./subconverter -g
sed -e '/^external-controller:/d' -e '/^socks-port:/d' -e '/^port:/d' -e '/^allow-lan:/d' -i config.yaml
sed '1s/^/tproxy-port: 7893\n/' -i config.yaml
# https://xtls.github.io/document/level-2/transparent_proxy/transparent_proxy.html
# https://gist.github.com/phlinhng/38a141862de775b10c613f7f2c6ade99
# https://wiki.nftables.org/wiki-nftables/index.php/Main_differences_with_iptables
# https://github.com/Dreamacro/clash/wiki/Configuration/a1d5c350643b51500cbdc78ab249f73aacb4cf2c
# https://github.com/MetaCubeX/Clash.Meta
# https://www.wogong.net/blog/2023/07/clash-gateway
# curl https://1.1.1.1/
# cat <<EOF >config.yaml
# somewhat
# EOF
fi
if [ "$1" = "" ]; then
cd inner
./clash -d .
exit
fi
