#!/bin/sh

cd $(dirname $0)

# Here's my way to fight against the GFW. Maybe not fit your preference.
# The init part. Execute "./gfw init" will run this part.

if [ "$1" = "init" ]; then
rm -rf inner ; mkdir inner
# Use clash-meta because many of the proxy providers (sometimes called as "airport" in chinese) uses modern protocol like vless + xtls that was not supported by classic clash. And, always uses only the core, but not any gui tools.
[ ! -e clash-meta.gz ] && curl -o clash-meta.gz -L https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.16.0/clash.meta-linux-amd64-v1.16.0.gz
cd inner
gzip -d <../clash-meta.gz >clash-meta
chmod +x clash-meta
fi

if [ "$1" = "fetch" ]; then
cd inner
rm -rf proxies
./clash-meta -d . -f ../fetch.yaml
fi

if [ "$1" = "run" ]; then
cd inner
rm -rf proxies
sudo ./clash-meta -d . -f ../config.yaml
fi

# https://blog.skk.moe/post/what-happend-to-dns-in-proxy/
# https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml
# https://github.com/MetaCubeX/Clash.Meta/blob/79626189f33631dc6bcd7d6503e2b2a5ff509453/common/convert/converter.go#L16
# https://community.nssurge.com/d/439-url-testtimeoutintervaltolerance-0
# https://github.com/shadowsocks/shadowsocks-org/blob/3363ad106a01ac905f5139e257646752c5f7be1a/docs/doc/sip002.md
# https://github.com/v2ray/Planning/issues/39
# https://github.com/XTLS/Xray-core/discussions/716
# https://wiki.metacubex.one/config/proxies/vless/
