#!/bin/sh
export ELECTRON_RUN_AS_NODE=1
export NPM_CONFIG_PREFIX=$(realpath $(dirname $0)/..)
exec $NPM_CONFIG_PREFIX/bin/electron $@

# https://registry.npmmirror.com/binary.html?path=electron/
# https://registry.npmmirror.com/-/binary/electron/v39.2.7/electron-v39.2.7-linux-x64.zip
# kkocdko@klp1:~/misc/apps/nodejs/bin$ ln -sf ../../../apps/electron/electron electron
# kkocdko@klp1:~/misc/apps/nodejs/bin$ ln -sf ../../../code/utils4linux/rt4web/electron-as-node node
