#!/bin/sh
if pidof chrome > /dev/null; then
echo skip set text-scaling-factor
else
gsettings set org.gnome.desktop.interface text-scaling-factor 1
nohup sh -c 'sleep 1.5 ; gsettings set org.gnome.desktop.interface text-scaling-factor 1.25' > /dev/null &
sleep 0.1
fi
GTK_IM_MODULE=ibus exec $(dirname $0)/chrome \
--disable-breakpad \
--disable-logging \
--disable-sync \
--disable-speech-api \
--disable-voice-input \
--disable-domain-reliability \
--disable-smooth-scrolling \
--disable-nacl \
--disable-quic \
--disable-crash-reporter \
--disable-chrome-tracing-computation \
--disable-component-update \
--disable-renderer-accessibility \
--disable-ax-menu-list \
--disable-top-sites \
--disable-features=WebGPU,TabHoverCardImages,ChromeRefresh2023,EyeDropper,CustomizeChromeSidePanel,OptimizationGuideModelDownloading \
--password-store=basic \
--force-device-scale-factor=1 \
--gtk-version=4 \
--force-dark-mode \
--force-local-ntp \
--extension-mime-request-handling=always-prompt-for-install \
--webrtc-ip-handling-policy=default_public_and_private_interfaces \
--ozone-platform=wayland \
--ozone-platform-hint=auto \
--enable-wayland-ime \
--wayland-text-input-version=3 \
--use-gl=angle \
--use-angle=vulkan \
--enable-zero-copy \
--enable-features=WebUIDarkMode,FluentOverlayScrollbar,VaapiVideoDecodeLinuxGL,VaapiVideoEncodeLinuxGL,WebRTCPipeWireCapturer,UseOzonePlatform,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,VaapiVideoDecoder,VaapiVideoEncoder,UseMultiPlaneFormatForHardwareVideo,VaapiVideoEncodeAccelerator \
"$@"

exit 1

cat <<EOF > /usr/share/applications/chromium.desktop
[Desktop Entry]
Version=1.0
Name=Chromium
Exec=/home/kkocdko/misc/apps/ungoogled-chromium/main %U
Terminal=false
Type=Application
Categories=Network;WebBrowser;
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
EOF

ln_to_tmp(){ from="$HOME/$2" ; to="/tmp/chromium_cache/$3" ; rm -rf "$from" ; if [ $1 = d ]; then mkdir -p "$(dirname "$from")" "$to" ; else touch "$to" ; fi ; ln -s "$to" "$from" ;}
ln_to_tmp d ".cache/chromium" main_cache
ln_to_tmp d ".config/chromium/GraphiteDawnCache" graphite_dawn_cache
ln_to_tmp d ".config/chromium/GrShaderCache" gr_shader_cache
ln_to_tmp d ".config/chromium/ShaderCache" shader_cache
ln_to_tmp d ".config/chromium/Default/GPUCache" gpu_cache
ln_to_tmp d ".config/chromium/Default/DawnWebGPUCache" dawn_webgpu_cache
ln_to_tmp d ".config/chromium/Default/DawnGraphiteCache" dawn_graphite_cache
ln_to_tmp d ".config/chromium/Default/Service Worker/CacheStorage" sw_cache_storage
ln_to_tmp d ".config/chromium/Default/Service Worker/ScriptCache" sw_script_cache
ln_to_tmp d ".config/chromium/Default/optimization_guide_hint_cache_store" opti_guide_cache
ln_to_tmp d ".config/chromium/segmentation_platform" segmentation_platform
ln_to_tmp f ".config/chromium/Default/DIPS" dips
ln_to_tmp f ".config/chromium/Default/DIPS-journal" dips_journal
ln_to_tmp f ".config/chromium/Default/History-journal" history_journal
ln_to_tmp f ".config/chromium/Default/Shortcuts-journal" shortcuts_journal
ln_to_tmp f ".config/chromium/Default/Network Action Predictor-journal" net_predictor_journal

if [ "$(id -u)" = "0" ]; then
echo "don't run as root please"
exit
fi

cd /home/kkocdko/misc/apps
rm -rf ungoogled-chromium
mkdir ungoogled-chromium
cd ungoogled-chromium
curl -o ungoogled-chromium.tar.xz -L https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/download/135.0.7049.114-1/ungoogled-chromium_135.0.7049.114-1_linux.tar.xz
tar -xf ungoogled-chromium.tar.xz --strip-components 1
rm -rf ungoogled-chromium.tar.xz
strip chrome
strip chromedriver
find locales/* -not -name 'en-US.*' -delete
chmod +x main

# chrome://media-internals/
# chrome://gpu/
# --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" # "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ... Edg/120.0.0.0"

# stable # Google Chrome	135.0.7049.95 (Official Build) unknown (64-bit)

mkdir -p /tmp/chromium-cache-tmp ~/.cache/chromium
sudo mount --bind /tmp/chromium-cache-tmp ~/.cache/chromium

# kkocdko@klp1:~/misc/apps/ungoogled-chromium$ ln -sf ../../code/utils4linux/rt4web/ungoogled-chromium-main main
