#!/bin/sh

cd $(dirname $0)

if [ "$1" = "" ]; then
$HOME/misc/apps/miniserve --header Cache-Control:no-store -p 9005 .
fi

if [ "$1" = "init" ]; then
if [ ! -e pdfjs-dist.zip ]; then
  curl -o pdfjs-dist.zip -L https://github.com/mozilla/pdf.js/releases/download/v3.10.111/pdfjs-3.10.111-dist.zip
fi
rm -rf pdfjs
unzip -qq -d pdfjs pdfjs-dist.zip
mv pdfjs/web/locale/en-US/viewer.properties pdfjs/web/locale/locale.properties
rm -rf \
  pdfjs/**/*.map \
  pdfjs/**/*.pdf \
  pdfjs/web/cmaps/ \
  pdfjs/web/locale/*/ \
  pdfjs/build/pdf.sandbox.js
cat >> pdfjs/web/booker.css << EOF
  ::-webkit-scrollbar {
    display: none;
  }
  html,
  body {
    scrollbar-width: none;
  }
  .toolbar:not(:hover) {
    opacity: 0;
  }
  #viewerContainer {
    top: 0 !important;
  }
  #viewer .page {
    /* 0 0 -250px; */
    --page-margin: 0 0 1px;
    --page-border: none;
    background: none !important;
  }
  html[x-text-enhance] .textLayer {
    opacity: 1;
  }
  html[x-text-enhance] .textLayer * {
    color: #000;
  }
  html[x-text-enhance][x-invert] .textLayer * {
    color: #fff;
  }
  html[x-invert] canvas {
    filter: brightness(0.77) contrast(2.4) hue-rotate(180deg) invert(1);
  }
EOF
cat >> pdfjs/web/booker.js << EOF
  addEventListener("keypress", ({ key: k }) => {
    if (k === "]") viewerContainer.scrollBy(0, innerHeight / 3);
    if (k === "[") viewerContainer.scrollBy(0, innerHeight / -3);
    if (k === "=") PDFViewerApplication.pdfViewer.currentScale += 0.01;
    if (k === "-") PDFViewerApplication.pdfViewer.currentScale -= 0.01;
  });
  const xopts = {};
  for (const [k, v] of new URLSearchParams(location.search))
    if (k.startsWith("x-"))
      document.documentElement.setAttribute(k, (xopts[k] = v || "true"));
  localStorage["pdfjs.preferences"] = JSON.stringify({
    ...(xopts["x-no-text-layer"] && { textLayerMode: 0 }),
    disableAutoFetch: true,
    disableStream: true,
  });
  // <button class=secondaryToolbarButton onclick=document.body.requestFullscreen()><span>Fullscreen</span></button>
  // viewBookmark.replaceWith()
EOF
sed -i pdfjs/build/pdf.js -e 's|CanvasGraphics;|&if(xopts["x-text-enhance"])CanvasGraphics.prototype.showText=()=>{};|'
sed -i pdfjs/web/images/toolbarButton-sidebarToggle.svg -e 's|/svg">|&<style>@media(prefers-color-scheme:dark){path{fill:white}}</style>|'
sed -i pdfjs/web/viewer.html -e 's|"utf-8">|&<script src=booker.js></script><link rel=stylesheet href=booker.css><link rel=icon href=images/toolbarButton-sidebarToggle.svg/>|'
rm -rf books
mkdir books
archive_dir="/run/media/kkocdko/data/docs/ebook"
ln -s "$archive_dir/Computer Networking A Top Down Approach 8th.pdf" books/cnatda.pdf
ln -s "$archive_dir/Computer Systems A Programmer s Perspective 3th.pdf" books/csapp.pdf
ln -s "$archive_dir/深入理解计算机系统（第三版）.pdf" books/csapp-zh.pdf
ln -s "$archive_dir/计算机网络自顶向下方法 第七版.pdf" books/cnatda-zh.pdf
ln -s "$archive_dir/算法竞赛入门经典 第2版.pdf" books/aoapc.pdf
ln -s "$archive_dir/HTTPS权威指南 在服务器和Web应用上部署SSL-TLS和PKI.pdf" books/bulletproof-ssl-and-tls-zh.pdf
fi

# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/books/bulletproof-ssl-and-tls-zh.pdf&x-text-enhance&x-invert
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/books/cnatda.pdf&x-text-enhance&x-invert
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/books/cnatda-zh.pdf&x-text-enhance&x-invert&x-no-text-layer
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/books/csapp-zh.pdf&x-text-enhance&x-invert&x-no-text-layer
