#!/bin/sh
cd $(dirname $0)

if [ ! -e dist ]; then
echo ">>> init"
mkdir dist
cd dist
echo ">>> download miniserve" # because python's http.server doesn't support http range
curl -o miniserve -L https://github.com/svenstaro/miniserve/releases/download/v0.24.0/miniserve-0.24.0-x86_64-unknown-linux-gnu
chmod +x miniserve
echo ">>> download and modify pdfjs"
curl -o pdfjs-dist.zip -L https://github.com/mozilla/pdf.js/releases/download/v4.0.269/pdfjs-4.0.269-dist.zip
unzip -qq -d pdfjs pdfjs-dist.zip
mv pdfjs/web/locale/en-US/viewer.ftl pdfjs/web/locale/viewer.ftl
sed -i pdfjs/web/locale/locale.json -e 's|/|/../|g'
sed -i pdfjs/web/images/toolbarButton-sidebarToggle.svg -e 's|/svg">|&<style>@media(prefers-color-scheme:dark){path{fill:white}}</style>|'
sed -i pdfjs/web/viewer.html -e 's|"utf-8">|&<script src=booker.js></script><link rel=stylesheet href=booker.css><link rel=icon href=images/toolbarButton-sidebarToggle.svg/>|'
sed -i pdfjs/build/pdf.mjs -e 's|(CanvasGraphics\.prototype|(xopts["x-text-enhance"]){CanvasGraphics.prototype.showText=()=>{}}if&|'
rm -rf \
  pdfjs/**/*.map \
  pdfjs/**/*.pdf \
  pdfjs/web/cmaps/ \
  pdfjs/web/locale/*/ \
  pdfjs/build/pdf.sandbox.mjs
cat <<EOF >pdfjs/web/booker.css
  ::-webkit-scrollbar {
    display: none;
  }
  html,
  body {
    scrollbar-width: none;
  }
  .toolbar:not(:hover) {
    opacity: 0;
  }
  #viewerContainer {
    top: 0 !important;
  }
  #viewer .page {
    /* 0 0 -250px; */
    --page-margin: 0 0 1px;
    --page-border: none;
    background: none !important;
  }
  html[x-text-enhance] :is(.textLayer, .textLayer *) {
    opacity: 1;
    color: #000;
  }
  html[x-text-enhance][x-invert] .textLayer * {
    color: #fff;
  }
  html[x-invert] canvas {
    filter: brightness(0.77) contrast(2.4) hue-rotate(180deg) invert(1);
  }
EOF
cat <<EOF >pdfjs/web/booker.js
  addEventListener("keypress", ({ key: k }) => {
    if (k === "]") viewerContainer.scrollBy(0, innerHeight / 3);
    if (k === "[") viewerContainer.scrollBy(0, innerHeight / -3);
    if (k === "=") PDFViewerApplication.pdfViewer.currentScale += 0.01;
    if (k === "-") PDFViewerApplication.pdfViewer.currentScale -= 0.01;
  });
  const xopts = {};
  for (const [k, v] of new URLSearchParams(location.search))
    if (k.startsWith("x-"))
      document.documentElement.setAttribute(k, (xopts[k] = v || "true"));
  localStorage["pdfjs.preferences"] = JSON.stringify({
    ...(xopts["x-no-text-layer"] && { textLayerMode: 0 }),
    disableAutoFetch: true,
    disableStream: true,
  });
  // <button class=secondaryToolbarButton onclick=document.body.requestFullscreen()><span>Fullscreen</span></button>
  // viewBookmark.replaceWith()
EOF
echo ">>> create symbolic links to books"
mkdir chunks
archive_dir="/run/media/kkocdko/data/docs/ebook"
ln -s "$archive_dir/Computer Networking A Top Down Approach 8th.pdf" chunks/cnatda.pdf
ln -s "$archive_dir/Computer Systems A Programmer s Perspective 3th.pdf" chunks/csapp.pdf
ln -s "$archive_dir/mysql-crash-course-zh.pdf" chunks/mysqlcc-zh.pdf
ln -s "$archive_dir/深入理解计算机系统（第三版）.pdf" chunks/csapp-zh.pdf
ln -s "$archive_dir/计算机网络自顶向下方法 第七版.pdf" chunks/cnatda-zh.pdf
ln -s "$archive_dir/算法竞赛入门经典 第2版.pdf" chunks/aoapc.pdf
ln -s "$archive_dir/HTTPS权威指南 在服务器和Web应用上部署SSL-TLS和PKI.pdf" chunks/bulletproof-ssl-and-tls-zh.pdf
ln -s "/home/kkocdko/misc/res/ipp_proj/html/SW64_Core4_指令系统手册-已处理.pdf" chunks/sw64-core4-asm-manual.pdf
ls chunks
exit
fi

if [ "$1" = "" ]; then
cd dist
./miniserve --header Cache-Control:no-store -p 9005 . # https://github.com/svenstaro/miniserve/releases/download/v0.24.0/miniserve-0.24.0-x86_64-unknown-linux-gnu
exit
fi

# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/chunks/bulletproof-ssl-and-tls-zh.pdf&x-text-enhance&x-invert
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/chunks/cnatda.pdf&x-text-enhance&x-invert
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/chunks/cnatda-zh.pdf&x-text-enhance&x-invert&x-no-text-layer
# http://127.0.0.1:9005/pdfjs/web/viewer.html?file=/chunks/csapp-zh.pdf&x-text-enhance&x-invert&x-no-text-layer

# trap exit INT
