#!/bin/sh

# I DO NOT MAKE PROMISES ABOUT THE LICENSE ISSUE!

docker kill qaac-0 ; docker rm qaac-0

docker run -d --network host --name qaac-0 debian:12 tail -f /dev/null
docker exec -it qaac-0 sh -c 'rm -rf /etc/apt/sources.list.d'
docker exec -it qaac-0 sh -c 'printf "deb http://mirrors.ustc.edu.cn/debian bookworm main\ndeb http://mirrors.ustc.edu.cn/debian bookworm-updates main\n" > /etc/apt/sources.list'
docker exec -it qaac-0 sh -c 'apt update ; apt install -y --no-install-recommends wine ; apt clean all ; rm -rf /var/lib/apt/lists'
docker exec -it qaac-0 sh -c 'cd /usr/lib/x86_64-linux-gnu ; rm -rf libapt* libgstreamer* libxml* libicudata* libx265* libSvtAv1Enc* libaom* libX11* libcrypto* libdav1d* librav1e* libgphoto2* libicuuc* libicui18n* libgnutls* libgio* perl-base gconv'
docker exec -it qaac-0 sh -c 'cd /usr/share/ ; rm -rf man doc locale fonts X11 zoneinfo iso-codes xml'
docker exec -it qaac-0 sh -c 'cd /usr/lib/x86_64-linux-gnu/wine/x86_64-windows ; rm -rf ieframe* mshtml* msxml* wined3d* d3d* d2d* opengl* dinput* dwrite* ddraw* xact* xaudio* x3daudio* xinput* xapofx* crypt* msi.dll jscript.dll vbscript.dll windowscodecs.dll actxprxy.dll comctl32.dll dbghelp.dll quartz.dll urlmon.dll gdiplus.dll wmphoto.dll winegstreamer.dll webservices.dll winhttp.dll light.msstyles spool drivers msvcp60.dll msvcr60.dll msvcp70.dll msvcr70.dll msvcp71.dll msvcr71.dll msvcp80.dll msvcr80.dll msvcp90.dll msvcr90.dll msvcp100.dll msvcr100.dll msvcp110.dll msvcr110.dll msvcp120.dll msvcr120.dll'
docker cp /home/kkocdko/misc/res/qaac_2.80_bundle qaac-0:/qaac_2.80_bundle
docker exec -it qaac-0 sh -c 'echo "#!/bin/sh" >> /usr/bin/qaac ; echo "WINEDEBUG=-all wine /qaac_2.80_bundle/qaac64.exe "\"\$@\" >> /usr/bin/qaac'
docker exec -it qaac-0 sh -c 'echo "#!/bin/sh" >> /usr/bin/refalac ; echo "WINEDEBUG=-all wine /qaac_2.80_bundle/refalac64.exe "\"\$@\" >> /usr/bin/refalac'
docker exec -it qaac-0 sh -c 'chmod +x /usr/bin/qaac ; chmod +x /usr/bin/refalac'
docker exec -it qaac-0 qaac --check
docker exec -it qaac-0 sh -c 'rm -rf /root/.wine/drive_c/windows/system32'
docker exec -it qaac-0 sh -c 'ln -s /usr/lib/x86_64-linux-gnu/wine/x86_64-windows /root/.wine/drive_c/windows/system32'
docker exec -it qaac-0 qaac --check
docker export qaac-0 | xz -c -v -T 2 -9 -e > qaac.tar.xz
ls -lh qaac.tar.xz
# rm -rf qaac.tar.zst
exit

# docker exec -it qaac-0 bash

# https://github.com/AnimMouse/QTFiles
# https://support.apple.com/en-us/HT210384
# https://secure-appldnld.apple.com/itunes12/001-97787-20210421-F0E5A3C2-A2C9-11EB-A40B-A128318AD179/iTunes64Setup.exe
# https://www.andrews-corner.org/qaac.html
# https://www.videohelp.com/software/qaac
# https://www.ljjyy.com/archives/2023/06/100639
