#!/bin/sh
if [ "$1" = "inner" ]; then
  # sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=http://download.example/pub/fedora/linux|baseurl=https://repo.huaweicloud.com/fedora|g' -i.bak /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo
  # mv fedora.repo.bak fedora.repo ; mv fedora-updates.repo.bak fedora-updates.repo
  find /etc/yum.repos.d -not -name 'fedora.repo' -not -name 'fedora-updates.repo' -not -name 'yum.repos.d' -delete
  dnf install lorax-lmc-novirt pykickstart -y --setopt=install_weak_deps=False --setopt=max_parallel_downloads=6
  cd /mkimg/fedora-kickstarts
  ksflatten -c custom.ks -o flat.ks
  livemedia-creator --no-virt --releasever 37 --ks flat.ks --resultdir /mkimg/result --make-iso --iso-only --compression zstd --compress-arg=-b --compress-arg=1M --compress-arg=-Xcompression-level --compress-arg=22
  exit
fi
git clone https://pagure.io/fedora-kickstarts --depth=1 --branch=f37
cp custom.ks fedora-kickstarts/custom.ks
sudo docker run --privileged -v `pwd`:/mkimg --name mkimg0 -i fedora:37 sh -c 'cd mkimg ; chmod +x mkimg ; ./mkimg inner'
