services:
  namenode:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3.3.6
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./:/opt/cur
  datanode:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3.3.6
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
  resourcemanager:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    # volumes:
    #   - ./test.sh:/opt/test.sh
  nodemanager:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3.3.6
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
