# Generated by pykickstart v3.48
#version=DEVEL
# Firewall configuration
firewall --enabled --service=mdns
# Keyboard layouts
keyboard 'us'
# System language
lang en_US.UTF-8
# Network information
network  --bootproto=dhcp --device=link --activate
# Shutdown after installation
shutdown
repo --name="fedora" --baseurl="http://192.168.43.82:9304/mirror/fedora/releases/38/Everything/x86_64/os/"
# Root password
rootpw --iscrypted --lock locked
# SELinux configuration
selinux --enforcing
# System services
services --disabled="sshd" --enabled="NetworkManager,ModemManager"
# System timezone
timezone US/Eastern
# Use network installation
url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch"
# X Window System configuration information
xconfig  --startxonboot
# System bootloader configuration
bootloader --location=none
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all
# Disk partitioning information
part / --size=4096

%post
# Enable livesys services
systemctl enable livesys.service
systemctl enable livesys-late.service

# enable tmpfs for /tmp
systemctl enable tmp.mount

# make it so that we don't do writing to the overlay for things which
# are just tmpdirs/caches
# note https://bugzilla.redhat.com/show_bug.cgi?id=1135475
cat >> /etc/fstab << EOF
vartmp   /var/tmp    tmpfs   defaults   0  0
EOF

# work around for poor key import UI in PackageKit
rm -f /var/lib/rpm/__db*
echo "Packages within this LiveCD"
rpm -qa --qf '%{size}\t%{name}-%{version}-%{release}.%{arch}\n' |sort -rn
# Note that running rpm recreates the rpm db files which aren't needed or wanted
rm -f /var/lib/rpm/__db*

# go ahead and pre-make the man -k cache (#455968)
/usr/bin/mandb

# make sure there aren't core files lying around
rm -f /core*

# remove random seed, the newly installed instance should make it's own
rm -f /var/lib/systemd/random-seed

# convince readahead not to collect
# FIXME: for systemd

echo 'File created by kickstart. See systemd-update-done.service(8).' \
    | tee /etc/.updated >/var/.updated

# Drop the rescue kernel and initramfs, we don't need them on the live media itself.
# See bug 1317709
rm -f /boot/*-rescue*

# Disable network service here, as doing it in the services line
# fails due to RHBZ #1369794
systemctl disable network

# Remove machine-id on pre generated images
rm -f /etc/machine-id
touch /etc/machine-id

%end

%post

# set livesys session type
sed -i 's/^livesys_session=.*/livesys_session="gnome"/' /etc/sysconfig/livesys

%end

%post --nochroot
curl -o adw-gtk3.tar.xz -L https://github.com/lassekongo83/adw-gtk3/releases/download/v4.9/adw-gtk3v4-9.tar.xz
tar -xf adw-gtk3.tar.xz -C /mnt/sysimage/usr/share/themes/
rm -f adw-gtk3.tar.xz
%end

%post
rm /usr/share/anaconda/gnome/fedora-welcome.desktop # disable welcome dialog
cat >> /usr/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.override << EOF
[org.gnome.desktop.interface]
gtk-theme="adw-gtk3"
font-name="Noto Sans 11"
document-font-name="Noto Sans 11"
monospace-font-name="Noto Sans Mono 10"
EOF
cat >> /usr/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.override << EOF
[org.gnome.desktop.wm.preferences]
titlebar-font="Noto Sans Bold 11"
EOF
cat >> /usr/share/glib-2.0/schemas/org.gnome.desktop.background.gschema.override << EOF
[org.gnome.desktop.background]
primary-color="#000000"
EOF
cat >> /usr/share/glib-2.0/schemas/org.gnome.desktop.peripherals.touchpad.gschema.override << EOF
[org.gnome.desktop.peripherals.touchpad]
tap-to-click=true
EOF
cat >> /usr/share/glib-2.0/schemas/org.gnome.TextEditor.gschema.override << EOF
[org.gnome.TextEditor]
spellcheck=false
EOF
glib-compile-schemas /usr/share/glib-2.0/schemas
systemctl disable dnf-makecache.service
systemctl disable dnf-makecache.timer
%end

%packages
@^workstation-product-environment
@anaconda-tools
anaconda
anaconda-live
dracut-live
epiphany
gnome-tweaks
isomd5sum
kernel
kernel-modules
livesys-scripts
-@container-management
-@dial-up
-@firefox
-@guest-desktop-agents
-@input-methods
-@libreoffice
-@printing
-@standard
-aajohan-comfortaa-fonts
-abrt
-abrt-*
-adobe-source-code-pro-fonts
-adwaita-qt5
-anaconda-install-env-deps
-avahi
-baobab
-bluez-cups
-cheese
-cpp
-cups
-cups-filters
-desktop-backgrounds-gnome
-device-mapper-multipath
-dnsmasq
-eog
-evince
-evince-djvu
-evince-nautilus
-fcoe-utils
-fedora-bookmarks
-fedora-workstation-backgrounds
-gamemode
-geolite2-*
-gfs2-utils
-ghostscript
-git
-glibc-all-langpacks
-gnome-backgrounds
-gnome-boxes
-gnome-calculator
-gnome-calendar
-gnome-characters
-gnome-classic-session
-gnome-clocks
-gnome-color-manager
-gnome-connections
-gnome-contacts
-gnome-font-viewer
-gnome-help
-gnome-logs
-gnome-maps
-gnome-photos
-gnome-remote-desktop
-gnome-shell-extension-background-logo
-gnome-software
-gnome-tour
-gnome-user-docs
-gnome-user-share
-gnome-weather
-google-noto-emoji-color-fonts
-gutenprint-cups
-hplip
-ibus-anthy
-ibus-hangul
-ibus-libzhuyin
-ibus-m17n
-ibus-typing-booster
-jomolhari-fonts
-kernel-modules-extra
-khmer-os-system-fonts
-liberation-*-fonts
-libsane-*
-lohit-*
-mediawriter
-nss-mdns
-orca
-paktype-naskh-basic-fonts
-qgnomeplatform-qt5
-qt5-*
-realmd
-reiserfs-utils
-rhythmbox
-rit-meera-new-fonts
-rygel
-sane-backends
-sane-backends-*
-sil-*-fonts
-simple-scan
-sos
-speech-dispatcher
-stix-fonts
-sushi
-tcpdump
-thai-scalable-waree-fonts
-thermald
-toolbox
-totem
-traceroute
-unoconv
-uresourced
-vazirmatn-vf-fonts
-whois
-words

%end
