#!/bin/sh
inner() { docker exec -it mkfedora0 $* ;}
docker run --privileged -d --network host --name mkfedora0 fedora:39 tail -f /dev/null
inner find /etc/yum.repos.d -not -name 'fedora.repo' -not -name 'fedora-updates.repo' -not -name 'yum.repos.d' -delete

# localhost
inner find /etc/yum.repos.d -not -name 'fedora.repo' -not -name 'yum.repos.d' -delete
inner sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=http://download.example/pub/fedora/linux/releases|baseurl=http://192.168.43.82:9304/mirror/fedora/development|g' -i /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo

inner dnf install lorax-lmc-novirt pykickstart git-core -y --setopt=install_weak_deps=False --setopt=max_parallel_downloads=6
inner git clone --depth=1 --branch=f39 https://pagure.io/fedora-kickstarts

# docker cp custom.ks mkfedora0:/fedora-kickstarts/custom.ks
# inner ksflatten -c /fedora-kickstarts/custom.ks -o flat.ks
docker cp custom.test.ks mkfedora0:/flat.ks

inner livemedia-creator --no-virt --releasever 39 --ks flat.ks --resultdir /result --make-iso --iso-only --compression zstd --compress-arg=-b --compress-arg=1M --compress-arg=-Xcompression-level --compress-arg=22
# docker cp mkfedora0:/result/ ./result/

# sudo -D `pwd` bash
# docker kill mkfedora0 ; docker rm mkfedora0
