#!/bin/sh
for device in $(ls /sys/class/hwmon); do
  cd /sys/class/hwmon/$device
  echo -n "- "
  tr [:upper:] [:lower:] < name
  for entry in $(ls | grep "_input$"); do
    v=0
    read v <$entry 2>/dev/null
    [ "$v" = "" ] && v=0
    # sed _input
    name=$(echo $entry | cut -d _ -f 1)
    echo -n $name
    if [ -e $name\_label ]; then
      echo -n _
      tr [:upper:] [:lower:] <$name\_label | tr -d \\n
    fi
    case "$name" in
      fan*)
        printf ": %d RPM\n" "$v"
        ;;
      freq*)
        printf ": %.0f MHz\n" "$(($v))e-6"
        ;;
      in*)
        printf ": %.3f V\n" "$(($v))e-3"
        ;;
      temp*)
        printf ": %.2f C\n" "$(($v))e-3"
        ;;
      *)
        # unknown
        echo ": value = $v"
        ;;
    esac
  done
done


# ~/misc/apps/hyperfine -w 5 -r 7 -p 'sleep 0.2' ./hwmoncat
