#!/bin/sh

cd /sys/class/hwmon
for device in `ls`; do
  echo "["`cat $device/name`"]" | sed "s/./\L&/g"
  for kind in "fan" "freq" "in" "temp"; do
    for i in `seq 0 9`; do
      if [ ! -e $device/$kind$i\_input ]; then
        continue
      fi
      v=`cat $device/$kind$i\_input`
      echo -n $kind$i
      if [ -e $device/$kind$i\_label ]; then
        echo -n "("`cat $device/$kind$i\_label | sed "s/./\L&/g"`")"
      fi
      [ $kind == "fan" ] && printf ": %d RPM\n" "$v"
      [ $kind == "freq" ] && printf ": %.0f MHz\n" "$(($v))e-6"
      [ $kind == "in" ] && printf ": %.3f V\n" "$(($v))e-3"
      [ $kind == "temp" ] && printf ": %.2f C\n" "$(($v))e-3"
    done
  done
  echo ""
done
