#!/bin/sh
prefix=_
for entry in /sys/class/hwmon/*/*_input; do
  case $entry in
    $prefix/*)
      ;;
    *)
      prefix=$(dirname $entry)
      read name < $prefix/name
      if [ -e $prefix/device/model ]; then
        read model < $prefix/device/model 2> /dev/null
        name="$name ($model)"
      fi
      echo "- $name" | tr [:upper:] [:lower:]
      ;;
  esac
  v=""
  read v < $entry 2> /dev/null
  name=$(basename $entry | cut -d _ -f 1)
  echo -n $name
  if [ -e $prefix/$name\_label ]; then
    echo -n _
    read label < $prefix/$name\_label
    echo -n $label | tr [:upper:] [:lower:]
  fi
  if [ "$v" = "" ]; then
    echo ": unknown"
    continue
  fi
  case "$name" in
    fan*)
      printf ": %d RPM\n" "$v"
      ;;
    freq*)
      printf ": %.0f MHz\n" "$(($v))e-6"
      ;;
    temp*)
      printf ": %.2f C\n" "$(($v))e-3"
      ;;
    power*)
      printf ": %.3f W\n" "$(($v))e-6"
      ;;
    in*)
      printf ": %.3f V\n" "$(($v))e-3"
      ;;
    *)
      echo ": $v"
      ;;
  esac
done
