#!/bin/sh
set -ex
trap exit INT
type unshare curl tar mksquashfs zstd pivot_root mkfs.fat mtools mmd mcopy qemu-system-x86_64 # apt install -y squashfs-tools mtools qemu-system-x86
temp_dir=/tmp/mkdebian
dist_dir=$(pwd)/dist
mkdir -p $temp_dir $dist_dir

if [ "$1" = test ]; then
  # init=/bin/bash -- -c "until cd /run/initramfs/live 2> /dev/null; do sleep 0.1; done; bash hi.sh" # printf "echo hi\nbash\n" > hi.sh
  # printf "root=UUID=a0b1-c2d3 rw rootflags=subvol=root,compress=zstd:1 mitigations=off audit=0 apparmor=0 selinux=0 amd_pstate=passive \0"
  # printf "root=/dev/disk/by-path/pci-0000:01:00.0-nvme-1-part2 rw mitigations=off audit=0 apparmor=0 selinux=0 \0"
  # printf "root=live:LABEL=KK_MAIN rd.live.dir=ventoy/boot rd.live.squashimg=debian_kk.squashfs rd.live.overlay.overlayfs=1 rw mitigations=off audit=0 apparmor=0 selinux=0 intel_iommu=off \0"
  printf "root=live:LABEL=QEMU_TEST rd.live.overlay.overlayfs=1 rw mitigations=off audit=0 apparmor=0 selinux=0 console=ttyS0 \0" | objcopy --update-section .cmdline=/dev/stdin $dist_dir/linux.efi
  truncate -s 0 $temp_dir/out.img
  truncate -s $(du -c $dist_dir/linux.efi $dist_dir/squashfs.img | awk 'END {print $1 + 3072}')K $temp_dir/out.img
  mkfs.fat -F 32 -n QEMU_TEST $temp_dir/out.img
  mmd -i $temp_dir/out.img ::/EFI ::/EFI/BOOT ::/LiveOS
  mcopy -i $temp_dir/out.img $dist_dir/linux.efi ::/EFI/BOOT/BOOTX64.EFI
  mcopy -i $temp_dir/out.img $dist_dir/squashfs.img ::/LiveOS/squashfs.img
  qemu-system-x86_64 \
    -machine q35,accel=kvm -bios /usr/share/ovmf/OVMF.fd -cpu host -smp 3 -m 4G \
    -display gtk,gl=on -device virtio-vga-gl -device qemu-xhci -device usb-tablet \
    -drive format=raw,file=$temp_dir/out.img
  exit
fi

if [ "$1" = build-cachyos-kernel-deb ]; then
  # curl -L https://packages.cachyos.org/package/cachyos-v3/x86_64_v3/linux-cachyos | awk -v RS='"' '/pkg.tar.zst/{print;exit}'
  curl --skip-existing -o $dist_dir/linux-cachyos.pkg.tar.zst -L https://cdn77.cachyos.org/repo/x86_64_v3/cachyos-v3/linux-cachyos-6.17.7-3-x86_64_v3.pkg.tar.zst
  mkdir -p $temp_dir/linux-cachyos-deb/data/boot $temp_dir/linux-cachyos-deb/control
  tar -xf $dist_dir/linux-cachyos.pkg.tar.zst --strip-components 1 -C $temp_dir/linux-cachyos-deb/data
  find $temp_dir/linux-cachyos-deb/data -name '*.zst' | xargs zstd --rm -q -d
  kver=$(ls $temp_dir/linux-cachyos-deb/data/lib/modules)
  mv $temp_dir/linux-cachyos-deb/data/lib/modules/$kver/vmlinuz $temp_dir/linux-cachyos-deb/data/boot/vmlinuz-$kver
  depmod -b $temp_dir/linux-cachyos-deb/data $kver
  tar -cf $temp_dir/linux-cachyos-deb/data.tar -C $temp_dir/linux-cachyos-deb/data .
  xz -T2 -9e --block-size $(du -sb $temp_dir/linux-cachyos-deb/data.tar | awk '{print $1/2+64}') $temp_dir/linux-cachyos-deb/data.tar # allow 2 threads decompress and still keep good ratio
  for entry in preinst prerm postinst postrm; do # simple scripts, copy from xanmod kernel
    printf '#!/bin/sh\nset -e\n# Pass maintainer script parameters to hook scripts\nexport DEB_MAINT_PARAMS="$*"\n# Tell initramfs builder whether it is wanted\nexport INITRD=Yes\ntest -d /etc/kernel/'$entry'.d && run-parts --arg="'$kver'" --arg="/boot/vmlinuz-'$kver'" /etc/kernel/'$entry'.d\nexit 0\n' > $temp_dir/linux-cachyos-deb/control/$entry
  done
  printf "Package: linux-image-$kver\nVersion: $kver\nArchitecture: amd64\nMaintainer: nobody\nSection: kernel\nDescription: Repacked cachyos x86_64_v3\n" > $temp_dir/linux-cachyos-deb/control/control
  tar -cJf $temp_dir/linux-cachyos-deb/control.tar.xz -C $temp_dir/linux-cachyos-deb/control .
  echo "2.0" > $temp_dir/linux-cachyos-deb/debian-binary
  rm -rf $dist_dir/linux-image.deb
  ar r $dist_dir/linux-image.deb $temp_dir/linux-cachyos-deb/debian-binary $temp_dir/linux-cachyos-deb/control.tar.xz $temp_dir/linux-cachyos-deb/data.tar.xz
  rm -rf $temp_dir
  exit
fi

if [ "$1" = build ]; then
  export ALL_PROXY=http://127.0.0.1:9091 ; export HTTP_PROXY=$ALL_PROXY ; export HTTPS_PROXY=$ALL_PROXY
  curl \
    -o $dist_dir/rootfs.tar.gz -L https://github.com/debuerreotype/docker-debian-artifacts/raw/06a7b511b90f4cc6c8b41d2f01a57702556fe63e/trixie/slim/oci/blobs/rootfs.tar.gz \
    -o $dist_dir/adw-gtk3.deb -L https://julianfairfax.codeberg.page/package-repo/debs/pool/main/a/adw-gtk3/adw-gtk3_6.2_all.deb \
    --parallel --skip-existing
  echo temp_dir=$temp_dir dist_dir=$dist_dir '
    . /etc/profile
    set -ex
    rm -rf $temp_dir/rootfs $dist_dir/linux.efi $dist_dir/squashfs.img
    mkdir -p $temp_dir/rootfs/oldroot
    tar -xf $dist_dir/rootfs.tar.gz -C $temp_dir/rootfs
    mount --bind $temp_dir/rootfs $temp_dir/rootfs # pivot_root requires a mountpoint to work
    mount -t tmpfs tmpfs $temp_dir/rootfs/dev # https://github.com/containers/bubblewrap/blob/v0.11.0/bubblewrap.c#L1378
    for entry in etc/resolv.conf etc/hosts proc dev/zero dev/random dev/urandom; do # omit dev/null
      touch $temp_dir/rootfs/$entry
      mount --bind /$entry $temp_dir/rootfs/$entry
    done
    mount --bind $dist_dir $temp_dir/rootfs/mnt
    cd $temp_dir/rootfs
    pivot_root . oldroot
    . /etc/profile
    set -ex
    ln -s /proc/self/fd/0 /dev/stdin
    ln -s /proc/self/fd/1 /dev/stdout
    ln -s /proc/self/fd/2 /dev/stderr
    ln -s /proc/self/fd /dev/fd
    export LANG=C.UTF-8 LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive
    printf "Types: deb\nURIs: http://192.168.1.189:9630/debian\nSuites: trixie trixie-updates trixie-backports\nComponents: main contrib non-free non-free-firmware\nSigned-By: /usr/share/keyrings/debian-archive-keyring.gpg\n\nTypes: deb\nURIs: http://192.168.1.189:9630/debian-security\nSuites: trixie-security\nComponents: main contrib non-free non-free-firmware\nSigned-By: /usr/share/keyrings/debian-archive-keyring.gpg\n\n# > https://help.mirrorz.org/debian/\n# http://mirrors.bfsu.edu.cn/debian # and -security\n# http://mirrors.ustc.edu.cn/debian # and -security\n" > /etc/apt/sources.list.d/debian.sources
    echo "Acquire::http::Pipeline-Depth \"0\";" > /etc/apt/apt.conf.d/99nopipelining
    apt-get update
    pkgs=""
    pkgs="$pkgs eject fdisk util-linux gdisk dhcpcd-base locales lsb-release netcat-openbsd procps python3" # apt info cloud-init | grep Depends:
    pkgs="$pkgs sudo libpam-systemd polkitd unattended-upgrades zstd apt-utils init nftables iputils-ping linux-sysctl-defaults less nano netbase vim-tiny whiptail systemd-timesyncd openssh-server ssh-import-id cloud-guest-utils apt-listchanges bash-completion bind9-host man-db manpages socat pciutils reportbug traceroute psmisc tcpdump ca-certificates curl ethtool uuid-runtime screen xz-utils" # from official cloud, exclude: systemd-resolved libnss-resolve libnss-myhostname netplan.io apparmor cloud-initramfs-growroot vim
    pkgs="$pkgs amd64-microcode intel-microcode atmel-firmware bluez-firmware dahdi-firmware-nonfree firmware-amd-graphics firmware-ast firmware-ath9k-htc firmware-atheros firmware-bnx2 firmware-bnx2x firmware-brcm80211 firmware-carl9170 firmware-cavium firmware-cirrus firmware-intel-graphics firmware-intel-misc firmware-intel-sound firmware-iwlwifi firmware-libertas firmware-linux-free firmware-linux-nonfree firmware-linux firmware-marvell-prestera firmware-mediatek firmware-misc-nonfree firmware-myricom firmware-netronome firmware-netxen firmware-nvidia-graphics firmware-qlogic firmware-realtek firmware-siano firmware-sof-signed firmware-zd1211" # from debian-live-testing-amd64-standard.iso, exclude: firmware-ivtv firmware-ipw2x00
    pkgs="$pkgs busybox-static util-linux-extra tmux binutils parted dosfstools systemd-boot-efi dracut-live dracut-config-generic" # extra packages, avoid install dracut hooks and dracut-network
    pkgs="$pkgs /mnt/linux-image.deb /mnt/adw-gtk3.deb"
    apt-get install -y --no-install-recommends $pkgs
    apt-mark hold plymouth hunspell-en-us aspell initramfs-tools yelp gnome-icon-theme gnome-sushi gnome-software gnome-contacts xserver-xorg fonts-droid-fallback fonts-noto-mono evolution-data-server gstreamer1.0-plugins-bad evince
    pkgs=""
    pkgs="$pkgs iproute2 iw network-manager"
    pkgs="$pkgs fonts-unifont gnome-calculator gnome-disk-utility gdm3 gnome-shell gnome-keyring gnome-menus gnome-session gnome-shell-extensions gnome-system-monitor ptyxis gnome-text-editor gvfs-fuse libpam-gnome-keyring libproxy1-plugin-gsettings nautilus pipewire-audio xdg-desktop-portal-gnome zenity gnome-remote-desktop" # apt info gnome-core | grep Depends:
    apt-get install -y --install-recommends $pkgs
    apt-mark unhold $(apt-mark showhold)
    # apt-get purge wsdd orca speech-dispatcher network-manager-l10n gnome-classic
    apt-get autoremove -y --purge
    apt-get clean all -y
    update-locale LANG=C.UTF-8 LC_ALL=C.UTF-8 # if you needs en_US.UTF-8, apt install locales-all
    for entry in apt-daily.timer apt-daily-upgrade.timer apt-listchanges.timer dpkg-db-backup.timer fwupd-refresh.timer man-db.timer display-manager.service; do
      ln -sf /dev/null /etc/systemd/system/$entry # equal to systemctl mask
    done
    rm -rf /usr/share/plymouth /var/lib/apt/lists/* /usr/share/desktop-base/*-theme /usr/share/ibus/dicts/emoji-* /usr/share/fonts/opentype/unifont/unifont_*
    echo "source /etc/vim/vimrc" > /etc/vim/vimrc.tiny
    printf "root\nroot\n" | passwd
    dracut --kver $(ls /lib/modules) --kernel-cmdline "$(printf %1024s)" --add dmsquash-live-autooverlay --aggressive-strip --omit-drivers "xfs bcachefs f2fs ocfs2 ocfs2_dlm ocfs2_nodemanager ceph libceph cifs lpfc kafs bfa fnic efct mpt3sas aic7xxx aic79xx qla2xxx qla4xxx intel_qat" --compress "zstd -9" --uefi /mnt/linux.efi
    # debug: mkdir -p /dev/pts ; mount -t devpts devpts /dev/pts ; ln -sf /dev/pts/ptmx /dev/ptmx ; busybox telnetd -F -b 127.0.0.1:9783 -l bash || true # busybox telnet 127.0.0.1 9783
  ' | unshare -mupfr --map-auto --mount-proc /bin/sh # after the unshare exited, all mounts were gone
  echo '
    if [ "$(id -u)" != "0" ]; then
      sleep 0.5 ; until gsettings get org.gnome.mutter auto-maximize 2> /dev/null; do sleep 0.2; done
      export $(tr "[:cntrl:]" " " < /proc/$(pgrep -u $(id -u) gnome-shell)/environ)
      gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
      gsettings set org.gnome.desktop.background primary-color "#35363a"
      gsettings set org.freedesktop.Tracker3.Miner.Files enable-monitors false
      systemctl --user mask localsearch-3
      exit
    fi
    if [ "$1" = "" -o $(expr index "$1" " ") != 0 ]; then echo "usage: bash $0 new_user_name" ; exit; fi
    user_obj=$(dbus-send --system --print-reply=literal --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.CreateUser string:$1 string:$1 int32:1)
    dbus-send --system --print-reply --dest=org.freedesktop.Accounts $user_obj org.freedesktop.Accounts.User.SetLocked boolean:false
    dbus-send --system --print-reply --dest=org.freedesktop.Accounts $user_obj org.freedesktop.Accounts.User.SetAutomaticLogin boolean:true
    passwd -d $1
    systemctl start gdm
    cat $0 | su $1 -l
    # todo: install to disk: cp -a /run/rootfsbase/* /mnt/sda1/
    # todo: why must use: tmux new -d bash de.sh live
  ' > $temp_dir/rootfs/root/de.sh
  echo temp_dir=$temp_dir dist_dir=$dist_dir '
    mksquashfs $temp_dir/rootfs $dist_dir/squashfs.img -b 1M -comp zstd -Xcompression-level 9 -e $temp_dir/rootfs/oldroot
    rm -rf $temp_dir
  ' | unshare -mupfr --map-auto --mount-proc /bin/sh
  exit
fi
