#!/bin/sh

if [ "$(whoami)" != "root" ]; then
    echo "Should be run as root."
    exit
fi
if [ "$(pwd)" != "$(dirname $(realpath $0))" ]; then
    echo "Should be run in current directory."
    exit
fi

if [ "$1" = "" ]; then
    name=mkdebian0
    # docker kill $name
    # docker rm $name
    # docker exec -it $name bash
    docker run --privileged -d --network host --name $name debian:testing-20230904 tail -f /dev/null
    docker cp $0 $name:/
    docker exec -it $name /$(basename $0) inner-docker
    exit
fi

[ "$1" != "inner-docker" ] && exit 1

# http://127.0.0.1:9304/mirror/debian/
# sed -i.bak 's|deb.debian.org|mirrors.ustc.edu.cn|g' /etc/apt/sources.list.d/debian.sources
sed -i.bak 's|deb.debian.org|127.0.0.1:9304/mirror|g' /etc/apt/sources.list.d/debian.sources
echo "'Acquire::http::Pipeline-Depth \"0\";" >/etc/apt/apt.conf.d/99nopipelining
apt update
apt install live-build
lb config -d bookworm --debian-installer live --debian-installer-distribution bookworm --archive-areas "main non-free-firmware" --debootstrap-options "--variant=minbase"
