# allow-lan: true
mixed-port: 7890 # used by apps that support proxy env vars, and tun is the fallback
ipv6: false
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
tun:
  enable: true
  stack: system
  dns-hijack: ["any:53"]
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  proxy-server-nameserver: ["tls://1.12.12.12:853", "tls://223.5.5.5:853"]
  nameserver-policy:
    "geosite:cn": ["tls://1.12.12.12:853", "tls://223.5.5.5:853"]
  nameserver: ["tls://1.1.1.1:853#proxy", "tls://8.8.8.8:853#proxy"]
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
rules:
  - GEOSITE,CN,DIRECT # Use dns-hijack with geosite instead of lots of annoy DOMAIN-SUFFIX rules
  - GEOIP,CN,DIRECT
  - IP-CIDR,1.1.1.1/32,DIRECT # VPS in China Aliyun
  - IP-CIDR,1.1.1.1/32,crucial-sg # VPS in Singapore
  - DOMAIN-SUFFIX,github.dev,crucial # GitHub Codespace
  - DOMAIN-SUFFIX,deepl.com,crucial
  - DOMAIN-SUFFIX,leetcode.com,crucial
  - DOMAIN-SUFFIX,update.googleapis.com,REJECT
  - MATCH,normal
# prettier-ignore
proxy-groups:
  - { name: normal, proxies: [foo-us-1-x0.1, foo-us-2-x0.1, DIRECT], type: select }
  - { name: crucial, proxies: [bar-jp, crucial-sg], type: select }
  - { name: crucial-sg, proxies: [bar-sg-x10], type: select }
# prettier-ignore
proxies:
  # foo - paid - cheap - https://foo
  - { name: foo-us-1-x0.1, server: 1.1.1.1, port: 443, type: trojan, password: pwd }
  - { name: foo-us-2-x0.1, server: 1.1.1.1, port: 443, type: trojan, password: pwd }
  # bar - paid - https://bar
  - { name: bar-jp, server: 1.1.1.1, port: 443, type: ss, password: pwd }
  - { name: bar-sg-x10, server: 1.1.1.1, port: 38200, type: vmess, password: pwd }
