#!/bin/sh
cd $(dirname $0)

if [ ! -e dist ]; then
  mkdir dist
  cd dist
  # curl -L https://github.com/SagerNet/sing-box/releases/download/v1.12.0/sing-box-1.12.0-linux-amd64.tar.gz | tar -xz --strip-component 1
  # cd ui; rm -f *.js *.ico *.png *.webmanifest *.ttf assets/*.ttf assets/*.woff assets/*.woff2; sed -i.bak "s|</title>|</title><script>requestAnimationFrame=f=>setTimeout(f,250)</script>|" index.html
  exit
fi

if [ "$1" = fetch ]; then
  node --experimental-default-type=module config-sub-fetch.js
  exit
fi

if [ "$1" = "" ]; then
  cd dist
  exec ./sing-box run -c config.jsonc -D .
  exit 1
fi

exit 1

echo '
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"><trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"><security><requestedPrivileges><requestedExecutionLevel level="requireAdministrator" uiAccess="false"/></requestedPrivileges></security></trustInfo></assembly>
' > sing-box.exe.manifest
echo '
cd /d %~dp0
curl -o config.jsonc -L "https://kkocdko.site/hidden/proxy/config.jsonc?token=xxx"
start "proxy" sing-box.exe run -c config.jsonc -D . --disable-color
' > main.bat

# ss -npt | grep 2400:c620 | sort
# https://120.53.53.53/resolve?type=A&name=qq.com // { "tag": "dhcp", "type": "dhcp" }
