#!/bin/sh
cd $(dirname $0)

if [ "$1" = "init" ]; then
[ ! -e sing-box.tar.gz ] && curl -o sing-box.tar.gz -L https://github.com/SagerNet/sing-box/releases/download/v1.6.6/sing-box-1.6.6-linux-amd64.tar.gz
rm -rf dist
mkdir dist
tar -xf sing-box.tar.gz --strip-components 1 -C dist
chmod +x ./dist/sing-box
fi

if [ "$1" = "fetch" ]; then
fi

if [ "$1" = "" ]; then
./dist/sing-box run -c ./config.jsonc -D ./dist
fi

# openssl req -newkey rsa:2048 -nodes -keyout trojan-key.pem -x509 -days 3650 -out trojan-cert.pem

# https://blog.skk.moe/post/what-happend-to-dns-in-proxy/
# https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml
# https://github.com/MetaCubeX/Clash.Meta/blob/79626189f33631dc6bcd7d6503e2b2a5ff509453/common/convert/converter.go#L16
# https://community.nssurge.com/d/439-url-testtimeoutintervaltolerance-0
# https://github.com/shadowsocks/shadowsocks-org/blob/3363ad106a01ac905f5139e257646752c5f7be1a/docs/doc/sip002.md
# https://github.com/v2ray/Planning/issues/39
# https://github.com/XTLS/Xray-core/discussions/716
# https://wiki.metacubex.one/config/proxies/vless/
