#!/bin/sh
cd $(dirname $0)
if [ ! -e ./nginx ]; then
mkdir -p ./nginx
curl -o ./nginx/nginx -L https://github.com/jirutka/nginx-binaries/raw/binaries/nginx-1.25.3-x86_64-linux
chmod +x ./nginx/nginx
fi
cd ./nginx
./nginx -p . -c ../nginx.conf
# ssh -R 10448:127.0.0.1:9458 root@1.1.1.1 # ensure "GatewayPorts yes" in /etc/ssh/sshd_config
# http://1.1.1.1:10448/?folder=/root/projects/hi
# https://serverfault.com/a/916736
# https://tutorials.tinkink.net/zh-hans/nginx/nginx-websocket-reverse-proxy.html
