#!/bin/sh
# My backup proposal:
# - Unidirectional data flow. Phone >[rsync+mtp]> PC >[rclone]> Cloud.
# - The code dir backup with history, others have no history.
alias dusort="du -ad 1 2>/dev/null | sort -n"
alias 7z="~/misc/apps/7z"
if [ "$(id -u)" = "0" ]; then
echo "Should be run as non-root."
exit
fi
if [ "$(pwd)" != "$(dirname $(realpath $0))" ]; then
echo "Should be run in current directory."
exit
fi

if [ "$1" = "pack-code-dir" ]; then
echo ">>> pack ~/misc/code directory"
rm -rf /tmp/bakcode/*
rsync --recursive --times --links --delete --filter=":- ~/misc/code/.rsyncignore" ~/misc/code /tmp/bakcode
password="7777" # code dir includes private keys and tokens, set a password to prevent auto-scanning
slimname="code_$(date +%Y%m%d)_p$password"
# slimname="code_20181014-20231106_p$password"
cd /tmp/bakcode
# 7z a -p$password -mhe=on -mx -myx -mmt=off -ms=on -mtm=off -mtc=off -mta=off -mtr=off -m0=LZMA2:d=384m:fb=273 -mmc=1000000000 $slimname.7z archive
7z a -p$password -mhe=on $slimname.7z code
exit
fi

if [ "$1" = "phone-to-pc" ]; then
echo ">>> sync from phone to pc, please reconnect mtp before this to ensure the cache cleared"
from_root="/run/user/1000/gvfs/mtp:host=LGE_LM-V409N_LMV409N1c42ce3d/Internal shared storage"
to_root="/run/media/kkocdko/data/archive/phone"
rsync_sync() { rsync --progress --recursive --times --links --delete "$from_root$1" "$to_root" ;}
rsync_sync /Pictures/Screenshots
rsync_sync /DCIM
rsync_sync /DataBackup
exit
fi

if [ "$1" = "pc-to-cloud" ]; then
rclone_sync() { ./dist/rclone --config rclone.conf sync --progress $1 onedrive_kkocdko:$2 ;}
rclone_sync /run/media/kkocdko/data/archive /rclone/archive
rclone_sync /run/media/kkocdko/data/media /rclone/media
rclone_sync /run/media/kkocdko/data/pkgs /rclone/pkgs
rclone_sync /run/media/kkocdko/data/software /rclone/software
exit
fi

if [ "$1" = "init-rclone" ]; then
mkdir -p dist
cd dist
curl -o rclone.zip -L https://github.com/rclone/rclone/releases/download/v1.66.0/rclone-v1.66.0-linux-amd64.zip
unzip -j rclone.zip
rm -f rclone.zip
cd ..
exit
fi
