#!/bin/sh
set -ex
trap exit INT

# My backup proposal: Unidirectional data flow. Phone -> PC -> Cloud. The code dir backup with history, others have no history.
alias rclone=/home/kkocdko/misc/apps/rclone # https://github.com/rclone/rclone/releases/download/v1.69.0/rclone-v1.69.0-linux-amd64.zip

if [ "$1" = pack-code-dir ]; then
  rclone sync --config "" --links --delete-excluded \
    --filter "- **/{dist,node_modules,target,venv}/" \
    --filter "- /clevert/temp/_test_res/" \
    --filter "- /clevert/temp/extensions/" \
    --filter "- /kblog/public/" \
    --filter "- /ripgrep/" \
    --filter "- /hello-cpp/build/" \
    --filter "- /hinapi/build/" \
    --filter "- /hinapi/third_party/" \
    --filter "- /tlsimple/3rdparty/" \
    --filter "- /tlsimple/src/ffi.rs" \
    /home/kkocdko/misc/code /tmp/pack-code-dir/code
  tar -c -C /tmp/pack-code-dir code | dd conv=swab of=/home/kkocdko/misc/bak/packed_code_$(date +%Y%m%d).tar.swab # prevent auto-scanning
  rm -rf /tmp/pack-code-dir
  exit
  # tips: 7z.exe a -snl -mmt=2 -mx9 packed_code_201810-202501.7z archive # dd conv=swab
fi

if [ "$1" = pack-apps-dir ]; then
  rm -rf /tmp/pack-apps-dir
  rclone sync --config "" --links --delete-excluded \
    --filter "- /{clangd,rclone,ffmpeg,esbuild,flashplayer,bombardier}" \
    --filter "- /frp/{frpc,frps}" \
    --filter "- /electron/" \
    --filter "+ /ungoogled-chromium/launch" \
    --filter "- /ungoogled-chromium/" \
    /home/kkocdko/misc/apps /tmp/pack-apps-dir/apps
  tar -c -C /tmp/pack-apps-dir apps | dd conv=swab of=/home/kkocdko/misc/bak/packed_apps_$(date +%Y%m%d).tar.swab
  rm -rf /tmp/pack-apps-dir
  exit
fi

if [ "$1" = pc-to-cloud ]; then
  # printf -- '[onedrive_kkocdko]\ntype = onedrive\ntoken = {"access_token":"xxx"}\ndrive_id = abc123\ndrive_type = personal\n' > rclone.conf
  export RCLONE_ONEDRIVE_DRIVE_TYPE='personal' RCLONE_ONEDRIVE_DRIVE_ID='xxx' RCLONE_ONEDRIVE_TOKEN='{"access_token":"xxx"}'
  # export RCLONE_CRYPT_REMOTE=':onedrive:/rclone_kk' RCLONE_CRYPT_PASSWORD='xxx' # rclone obscure the_password
  rclone sync --config "" --progress --checksum --delete-excluded \
    --filter "- /apps/" \
    --filter "- /code/" \
    --filter "- /temp/" \
    /home/kkocdko/misc :onedrive:/rclone
  exit
fi

if [ "$1" = phone-to-pc ]; then
  rclone_sync() { rclone sync --config "" --progress --webdav-url http://192.168.192.92:8181 :webdav:/$1 /home/kkocdko/misc/bak/kpa1/$1 ;}
  rclone_sync Pictures
  rclone_sync DCIM
  rclone_sync Download
  # rclone_sync DataBackup # direct to pc using webdav, don't sync here # rclone --config "" serve webdav --addr :9439 /home/kkocdko/misc/bak/kpa1/
  # todo: exclude .thumbnails and others?
  exit
fi

exit 1
