#!/bin/sh
set -ex
trap exit INT

# My backup proposal:
# - Unidirectional data flow. Phone > PC > Cloud.
# - The code dir backup with history, others have no history.
alias rclone=/home/kkocdko/misc/apps/rclone # https://github.com/rclone/rclone/releases/download/v1.69.0/rclone-v1.69.0-linux-amd64.zip
alias rsync=/home/kkocdko/misc/apps/rsync # https://github.com/kkocdko/utils4linux/releases/tag/mksb.rsync_3.3.0_8846311740
alias 7zz=/home/kkocdko/misc/apps/7zz
alias dusort="du -a -d 1 2> /dev/null | sort -n"

if [ "$1" = pack-code-dir ]; then
  echo "do this step manually please"; exit
  rm -rf /tmp/pack-code-dir
  rsync --recursive --times --links --delete --filter=":- /home/kkocdko/misc/code/.rsyncignore" /home/kkocdko/misc/code /tmp/pack-code-dir
  password="7777" # code dir includes private keys and tokens, set a password to prevent auto-scanning
  slimname="code_$(date +%Y%m%d)_p$password"
  cd /tmp/pack-code-dir
  # 7z a -p$password -mhe=on -mx -myx -mmt=off -ms=on -mtm=off -mtc=off -mta=off -mtr=off -m0=LZMA2:d=384m:fb=273 -mmc=1000000000 $slimname.7z archive
  7zz a -p$password -mhe=on $slimname.7z code
  exit
fi

if [ "$1" = pc-to-cloud ]; then
  rclone_sync() { rclone --config rclone.conf sync --progress $1 onedrive_kkocdko:$2 ;}
  rclone_sync /home/kkocdko/misc/bak /rclone/bak
  rclone_sync /home/kkocdko/misc/media /rclone/media
  rclone_sync /home/kkocdko/misc/res /rclone/res
  exit
fi

if [ "$1" = phone-to-pc ]; then
  from_root=rsync://192.168.192.92:9426/sdcard # use phone's wifi hotspot, which is fastest
  to_root=/home/kkocdko/misc/bak/kpa1
  rsync $from_root/ # will print the list
  rsync_sync() { rsync --checksum --progress --recursive --times --links --delete "$from_root$1" "$to_root" ;}
  rsync_sync /Pictures
  rsync_sync /DCIM
  rsync_sync /Download
  # rsync_sync /DataBackup # direct to pc using webdav, don't sync here # ~/misc/apps/dufs -A /home/kkocdko/misc/bak/kpa1/
  # todo: exclude .thumbnails and others?
  exit
fi

exit 1

# paste below to the "anywhere" app, remember to check "execute with root". recommend to use with `anywhere settings > show shell result > dialog`
if pgrep rsync; then
  killall rsync
  sleep 0.1
  rm -rf /data/_shell/rsync
else
  mkdir -p /data/_shell/rsync
  cd /data/_shell/rsync
  cp /sdcard/Download/_shell/rsync ./rsync
  chmod +x ./rsync
  # why uid = 0 ? what i think about at that time?
  printf -- "uid = 0\ngid = 0\nuse chroot = no\nfake super = yes\nread only = false\n[sdcard]\npath = /sdcard\n" > rsyncd.conf
  nohup ./rsync --daemon --no-detach --port=9426 --config=rsyncd.conf --log-file=rsyncd.log </dev/null >/dev/null 2>&1 &
  ip a | grep "inet " | grep -v 127.0.0.1
fi

# these are some tips
su shell -c "cmd notification post -S bigtext ip '$(ip a | grep "inet " | grep -v 127.0.0.1)'"
# todo: other things like chromium data
