#!/bin/sh
if [ `whoami` != "root" ]; then
  sudo $0 $*
  exit
fi
/home/kkocdko/misc/apps/lenopow disable
while true; do
  read -rd "" v </sys/class/hwmon/hwmon1/device/capacity
  printf "$(date +%H:%M:%S) - "
  if [ $v -gt 70 ]; then
    sudo /home/kkocdko/misc/apps/lenopow enable
    echo "greater"
    exit
  else
    echo "less"
  fi
  sleep 5
done
