#!/bin/sh
set -e
trap exit SIGINT
cd dist
cat <<'EOF' > nginx.conf
daemon off;
pid ./pid;
events { worker_connections 64; }
http {
  access_log off;
  fastcgi_temp_path ./temp;
  uwsgi_temp_path ./temp;
  scgi_temp_path ./temp;
  client_body_temp_path ./temp;
  proxy_temp_path ./temp;
  proxy_cache_path ./proxy_cache_path inactive=999d keys_zone=c0:10m loader_threshold=900 loader_files=900;
  upstream u0 { server mirrors.ustc.edu.cn; keepalive 8; }
  server {
    listen 9630;
    location / {
      proxy_pass http://u0;
      proxy_http_version 1.1;
      proxy_set_header Host mirrors.ustc.edu.cn;
      proxy_set_header Referer "";
      proxy_set_header Connection "";
      proxy_set_header Accept-Encoding "";
      proxy_ignore_client_abort on;
      proxy_cache c0;
      proxy_cache_key $scheme://$uri$is_args$query_string;
      proxy_cache_valid 999d;
      proxy_cache_bypass $arg_should_bypass_cache;
    }
  }
}
EOF
exec ~/misc/apps/nginx -e ./error_log -c nginx.conf -p .
# http://nginx.org/packages/debian/pool/nginx/n/nginx/nginx_1.26.2-1~bookworm_amd64.deb
