#!/bin/sh
file="/home/kkocdko/misc/media/audio/listen/童话镇__陈一发儿__暗杠.m4a"
file="/home/kkocdko/misc/media/audio/listen/破旧世界.mid.mp3"
# file="/home/kkocdko/misc/media/audio/listen/apt__rose.m4a"
[ "$1" != "" ] && file="$1"
~/misc/apps/ffmpeg -y -hide_banner -i $file -ac 1 /tmp/listen.wav
ls -lh /tmp/listen.wav
while true; do
pw-cat -p /tmp/listen.wav || exit 1
done
# dnf install pipewire-utils
# http://trac.ffmpeg.org/wiki/audio%20types
# https://superuser.com/q/826669/
