#!/bin/sh
file="/run/media/kkocdko/data/media/audio/listen/童话镇-陈一发儿.m4a"
[ "$1" != "" ] && file="$1"
~/misc/apps/ffmpeg -y -hide_banner -i $file -ac 1 /tmp/listen.wav
ls -lh /tmp/listen.wav
while [ "" = "" ]; do
pw-cat -p /tmp/listen.wav || exit 1
done
# dnf install pipewire-utils
# http://trac.ffmpeg.org/wiki/audio%20types
# https://ffmpeg.org/ffmpeg.html
# https://superuser.com/q/826669/
