#!/bin/sh
curl \
  -o hmcl.jar -L https://github.com/HMCL-dev/HMCL/releases/download/release-3.6.12/HMCL-3.6.12.jar \
  -o jre.tar.gz -L https://mirrors.ustc.edu.cn/adoptium/releases/temurin21-binaries/jdk-21.0.7%2B6/OpenJDK21U-jre_x64_linux_hotspot_21.0.7_6.tar.gz \
  --parallel
mkdir jre
tar -xf jre.tar.gz --strip-components 1 -C jre
mkdir -p .openjfx ~/.openjfx
sudo mount --bind .openjfx ~/.openjfx
HOME="$(pwd)" ./jre/bin/java -Dhmcl.home="$(pwd)" -jar hmcl.jar
# https://github.com/CaffeineMC/sodium
# https://github.com/CaffeineMC/lithium
