name: fdkaac
on:
  workflow_dispatch:
jobs:
  fdkaac:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run: |
          curl -o fdkaac.tar.gz -L https://github.com/nu774/fdkaac/archive/f95566ee8ed1623e0d683cc94ca5f50c897bef79.tar.gz
          mkdir -p fdkaac
          cd fdkaac
          tar -xf ../fdkaac.tar.gz --strip-component 1
          sed -i Makefile.am -e 's|-lfdk-aac|-l:libfdk-aac.a|'
          sudo apt -y install libfdk-aac-dev # must be above libfdk-aac-dev_2.0.2-1_amd64.deb
          autoreconf -fiv
          ./configure
          make
          mv ./fdkaac /tmp/fdkaac
          strip -s /tmp/fdkaac
          ldd /tmp/fdkaac || printf "" # avoid ldd returns non-zero code
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/fdkaac
