name: mkfedora
# on:
#   release:
#     types: [created]
jobs:
  mkfedora:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cd mkfedora ; chmod +x mkfedora ; script -c './mkfedora' /dev/null
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mkfedora/result/boot.iso
