name: release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        run: git clone --depth=1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Build Docker Image
        run: cd makeimage && docker build -t makeimage .
      - name: Run Build
        run: docker run --network=host --privileged -v $(pwd):$(pwd) --name makeimage-0 makeimage $(pwd)/makeimage/custom.ks $(pwd)/result --compression zstd --compress-arg=-b --compress-arg=1M --compress-arg=-Xcompression-level --compress-arg=22
      - name: Release File
        uses: softprops/action-gh-release@v1
        with:
          files: result/boot.iso
